---
driver:
  name: docker
platforms:
  - name: oracle-amb-host
    groups:
      - ultimate
      - amb
    children:
      - oracle_swarm
    image: ubuntu:16.04
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  playbooks:
    prepare: ../prepare.yml
    converge: ../ultimate-commons/converge.yml
  inventory:
    host_vars:
      oracle-amb-host:
        ORACLE_VALIDATOR_KEYSTORE_PATH: "../../../e2e-commons/keystore_ultimate.json"
        ORACLE_VALIDATOR_KEYSTORE_PASSWORD: "12345678"
verifier:
  name: testinfra
scenario:
  name: ultimate-amb
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
